#ifndef STATBAR_DATA_
#define STATBAR_DATA_

#define IMG_STATBAR_WIDTH 120
#define IMG_STATBAR_HEIGHT 480
#define STATBAR_START_X (640-IMG_STATBAR_WIDTH)
#define STATBAR_START_Y 0

#endif STATBAR_DATA_